---
title: "Рекомендации для Reseach Proposal"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
date: "2022-23"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Составление Research proposal (aka "Предложение по исследованию") является первым содержательным этапом при подготовке курсовой/ВКР. 

Как правило, Research proposal включает в себя описание следующих элементов: 

1. **Исследовательский вопрос**: что хотите исследовать, и почему этот вопрос интересен (мотивация исследования, в идеале --- со ссылками на литературу). Отталкивайтесь от интересного явления, которое хотите объяснить или исследовать.

2. Выдвигаемые **гипотезы** относительно исследовательского вопроса (формулировка в обычном, смысловом контексте). Обоснование гипотез --- почему и из каких соображений они выдвигаются: какой механизм обеспечивает те причинно-следственные связи, которые лежат в основе ваших гипотез. Здесь тоже в идеале нужно использовать при аргументации ссылки на литературу.

4. Какие **данные** для этого понадобятся или уже собраны: что должно быть единицей наблюдения, какая должна быть выборка, какой тип данных. Потенциальный или фактический **источник данных** (или источники), т. е. база данных, на которой такое исследование может быть проведено: название, описание (что, кем, когда и как собиралось, измерялось, описывалось и т.п.), ссылка на страницу в интернете (например это может быть Всемирный банк, база данных ФРС, Росстат, RLMS и т. п.). В качестве источника данных в некоторых случаях могут выступать также самостоятельно собранные данные, в том числе опросные, их тоже нужно подробно описывать (привести анкету или метод сбора).

5. Какие **переменные**, т. е. характеристики (признаки) объектов наблюдения необходимы. Какие переменные доступны в имеющихся источниках: за какой период, для какой выборки. Описание этих переменных (единицы измерения, особенности измерения и т. п.). Какие из них являются переменными интереса, а какие --- контрольными переменными. 

6. Спецификация **модели**: набор регрессоров, форма зависимости. Обоснование модели (из общих смысловых и экономических соображений). 

7. **Эконометрическая формулировка гипотез**: постановка гипотез в содержательной, модельной и нормальной параметрической формах. Выбор и обоснование критерия для проверки гипотез. 

8. **Policy Conclusions** (возможные практические применения результатов исследования): кому результаты такого исследования могут быть полезны и как их можно использовать.