---
title: "Рекомендации по структуре и разделам курсовых и дипломных работ"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
date: '2022-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Для эмпирических курсовых/ВКР я рекомендую примерно следующую структуру (она может меняться в зависимости от области исследований и хода вашей работы): 

1. **Введение**
	a. Мотивация: почему то, что вы изуаете важно
	b. Может включать в себя краткий обзор основных исследований по теме
	c. Исследовательский вопрос, исследовательская гипотеза, экономический механизм, обосновывающий гипотезу
2. **Обзор литературы** (иногда)
3. **Контекст**
	a. Описание особенностей развития какой-либо сферы, отрасли, национальных особенностей
	b. Может включать обзор литературы про Россию
4. **Данные и переменные**
	a. Описание источников, датасета, процесса сбора
	b. Описание переменных (зависимой переменной, переменной интереса, контрольных переменных и т. п.)
	c. Описательные статистики
5. **Методология**
	a. Регрессионные модели
	b. Стратегия оценивания
	c. Может включать в себя описание программного обеспечения, использованного при работе, ссылки на код, исходные данные и т. п.
6. **Результаты**
	a. Описательные/предварительные результаты (иногда)
	b. Основные результаты
	c. Robustness checks (различные проверки, призванные подвердить, что ваши результаты являлются устойчивыми при изменении спецификаций, данных и т. п.
7. **Заключение**
	a. Подведение итогов
	b. Обсуждение результатов (их экономическая осмысленность, сопоставление с результатами предыдущих исследований)
	c. Рекомендации на основе полученных результатов (как и кто их может использовать?)
	d. Направления для будущих исследований
	e. Угрозы внутренней и внешней валидности исследования
