---
title: "История курсовых и дипломных работ под моим руководством"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
date: '2022-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

Здесь можно посмотреть, на какие темы писали студенты под мои руководством и какие оценки за них получили. 

| Учебный год | Тип работы | Тема | Оценка |
|---|---|---|---|
| 2018-19 | Курсовая | Влияние инноваций на экономический рост страны | 7 |
| 2019-20 | Курсовая | Институты и неравенство: эмпирический анализ российских регионов | 7 |
| 2019-20 | ВКР | Демократические институты и инновационное развитие фирм: анализ данных по регионам России | 5 |
| 2019-20 | ВКР | Инновации и экономический рост: эмпирический анализ стран мира | 6 |
| 2019-20 | ВКР | Эконометрический анализ влияния инноваций на экономический рост в российских регионах | недопуск |
| 2020-21 | Курсовая | Смена губернатора и региональные экономические показатели: эмпирический анализ | 9 |
| 2020-21 | Курсовая | Психическое здоровье и неравенство доходов: эмпирический анализ стран мира | 9 |
| 2020-21 | Курсовая | Эмпирическая оценка межрегиональной мобильности капитала в России | 3 |
| 2020-21 | Курсовая | Детское здоровье и доходы родителей: эмпирический анализ российских домохозяйств | 9 |
| 2020-21 | ВКР | Эмпирический анализ обусловленного доходами неравенства здоровья среди детей Российской Федерации | 7 |
| 2020-21 | ВКР | Гендерные различия в потребительских предпочтениях: эмпирический анализ рынка фитнес-услуг в РФ | 8 |
| 2020-21 | ВКР | Экономический рост и цифровизация: эмпирический анализ российских регионов | 7 |
| 2021-22 | Курсовая | Экономический рост и культурное многообразие: эмпирический анализ российских регионов | 7, 8 |
| 2021-22 | Курсовая | Разнообразие видов деятельности и экономический рост: эмпирический анализ российских регионов | 7 |
| 2021-22 | Курсовая | Анализ пространственной конкуренции продуктового ритейла | 8 |
| 2021-22 | ВКР | Эмпирическая оценка спроса на продукты питания в России | 9 |
| 2021-22 | ВКР | Детское здоровье и доходы родителей: эмпирический анализ российских домохозяйств | 9 |
