---
title: "Рекомендации по выполнению различных этапов курсовых и дипломных работ"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
date: '2022-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

РАЗДЕЛ БУДЕТ ПОПОЛНЯТЬСЯ ПО ХОДУ УЧЕБНОГО ГОДА

## Поиск и обзор литературы

Количество источников в списке литературы никак не регламентируется, но по моей субъективной оценке в вашем списке литературы должно быть хотя бы 20 источников, большинство из которых --- англоязычные эмпирические, опубликованные в хороших журналах. 

Критерий, который я могу предложить для определения хороших журналов, такой. Журнал должен находиться в первом или втором квартиле (Q1 или Q2) в области "Economics, Econometrics". Квартили журналом рекомендую смотреть на сайте [SJR](https://www.scimagojr.com/).

В процессе чтения эмпирических статей я рекомендую заносить ключевую информацию о них в таблицу [примерно такого вида](https://docs.google.com/spreadsheets/d/10Lcw_3SHWKwL8YY8o91tbtVE0EdSW14gPCcQzxEJzfw/edit?usp=sharing). 

При оформлении ссылок на литературу, а также списка литературы предпочтителен APA-style. Примеры оформления можно посмотреть по [ссылке](https://www.scribbr.com/category/apa-examples/).

## Структура работы

Строгих требований к структуре курсовой/ВКР нет. Общее требование --- структура должна быть ясной и понятной, способствовать логичному изложению мысли.

Часто структура научной работы зависит области, в которой проводится исследование. Поэтому основным источником вдохновения для вас могут быть научные статьи по вашей теме. По мере ознакомления со статьями, у вас должно сложиться общее впечатление о том, какая структура принята в области, к которой относится ваша работа.

Как правило, каким-то образом обособляются следующие элементы работы: 

- Введение

- Обзор литературы

- Методы

- Данные

- Результаты

- Заключение

Иными словами, вы должны раскрыть в своей работе: 

- зачем вы это делали (введение)

- что и как вы делали (методы)

- с чем вы это делали (данные)

- что в итоге получили (результаты и заключение)

Если уточнять, то для эмпирических курсовых/ВКР я рекомендую примерно следующую структуру, с которой можно ознакомиться по [ссылке](structure.html). 

