---
title: "Темы курсовых и дипломных работ"
output:
  prettydoc::html_pretty:
    theme: architect
    highlight: github
date: '2022-23'
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

На этой страничке представлены темы для курсовых и ВКР, которые я предлагаю писать под моим руководством, а также некоторые комментарии к ним. 
Перечень предварительный, а темы могут корректироваться по итогам переговоров. Помимо этого Вы можете сформулировать тему самостоятельно, но в этом случае вам придется убедить меня в том, что тема интересная и важная, а также взять на себя дополнительную ответственность по работе над неизвестной мне темой.

Традиционно мои исследовательские интересы лежат в области региональной экономики, в частности регионального экономического роста и региональных инноваций. Другая давняя сфера моих интересов --- институциональная экономика. В последнее время мои интересы смещаются в область эмпирики отраслевых рынков и исследований ритейла, в частности оценки спроса и конкуренции. 

Исходя из моих интересов и сформированы многие темы работ, которые можно писать под моим руководством. Они условно делятся на три блока. 


## Исследования экономики (российских) регионов

Все исследования в этой области предполагают самостоятельный сбор данных о регионах России. Их базовые характеристики доступны в сборнике Росстат ["Регионы России"](https://rosstat.gov.ru/folder/210/document/13205). Дополнительные показатели придется собирать в "полуручном" режиме, но я могу подсказать некоторые источники. 

Чаще всего нужно будет работать с панельными данными, т. е. данными о российских регионах за несколько лет. Также необходимо помнить, что регионы вряд ли являются случайной выборкой, что предполагает учитывать и это в анализе, используя модели, учитывающие пространственную корреляцию. 

Потенциальные темы для работы: 

* Эмпирическая оценка эффективности инновационной политики в российских регионах / Empirical Estimation of Innovation Policy Effectiveness in Russian Regions

* Институты и экономический рост: эмпирический анализ российских регионов / Institutions and Economic Growth: An Empirical Analysis of Russian Regions

* Экономическое развитие в условиях пандемии: эмпирический анализ российских регионов / Economic Development in Times of Pandemic: An Empirical Analysis of Russian Regions



## Исследования (российских) домохозяйств

Исследования домохояйств основывают на данных опросов. Самый изветсный источник данных в этой области --- [Российский мониторинг экономического положения и здоровья населения НИУ ВШЭ](https://www.hse.ru/rlms/). Если вы хотите работать с данными о российских домохозяйствах, то одним из первых этапов вашей работы станет загрузка и обработка таких данных (что-то в процессе работы я смогу подсказать).

Потенциальные темы для работы: 

* Детское здоровье и занятость родителей: эмпирический анализ российских домохозяйств / Children's Health and Parental Employment: An Empirical Analysis of Russian Households

* Разнообразие рациона и собственное производство пищи: эмпирический анализ российских домохозяйств / Dietary Diversity and Own Food Production: An Empirical Analysis of Russian Households

* Эмпирическая оценка спроса на сахаросодержащие продукты в России / Empirical Estimation of Demand for Sugar-Containing Products in Russia


## Исследования (российского) ритейла

Для работы по этим темам привлекаются в первую очередь очень ответственные студенты с высоким рейтингом. 

Темы этого блока наиболее сложные, т. к. предполагают работу со сложными и "сырыми" данными о пространственном спросе и конкуренции в области ритейла, а также хорошие знания в области микроэкономики, теории игр и желание самостоятельно осваивать продвинутые эконометрические техники. 

Более того, эти темы предполагают работу с коммерческими данными, поэтому для начала нужно будет получить согласие от владельца данных и подписать соглашение о неразглашении. 


Потенциальные темы для работы: 

* Эмпирический анализ пространственной конкуренции между сетевыми ритейлерами в Санкт-Петербурге / Empirical Analysis of Spatial Competition between Chain Retailers in St. Petersburg

* Эмпирический анализ пространственного спроса на продукты питания в Санкт-Петербурге / Empirical Analysis of Spatial Demand for Groceries in St. Petersburg







